### ISSUE TITLE
Seeing an error popup any time I click anything in the UI

### ISSUE THREAD

**Issue by mudboy** [Novik/ruTorrent#1374]
**ruTorrent** 3.7
**chrome** 55.0.2883.87

The error is shown in this screen shot, Bad response from server: (0 [error,setuisettings])

![rutorrenterror](https://cloud.githubusercontent.com/assets/2846/21388381/f7a991b8-c773-11e6-9814-224e476b6598.png)

Using the the inspector I discovered that it is failing to send the request and the following stacktrace shows the cause

```
URIError: URI malformed
at decodeURI (<anonymous>)
at XMLHttpRequest.send (chrome-extension://hdokiejnpgwwkedhajhdlcewhuplioahd/xhrExtension.js:2:51)
at Object.send (https://xx.xx.xx.xx/rutorrent/js/jquery.js:5:25682)
at Function.ajax (https://xx.xx.xx.xx/rutorrent/js/jquery.js:5:21570)
at Ajax (https://xx.xx.xx.xx/rutorrent/js/rtorrent.js:1099:4)
at Object.requestWithTimeout (https://xx.xx.xx.xx/rutorrent/js/webui.js:2459:3)
at Object.request (https://xx.xx.xx.xx/rutorrent/js/webui.js:2454:8)
at dxSTable.save (https://xx.xx.xx.xx/rutorrent/js/webui.js:776:12)
at dxSTable.resizeColumn (https://xx.xx.xx.xx/rutorrent/js/stable.js:404:8)
at dxSTable.resizeHack (https://xx.xx.xx.xx/rutorrent/js/stable.js:324:8)
```

It doesn't stop me from using ruTorrent, everything still works fine, but it is very annoying.

Here is the uri:

```
https://xx.xx.xx.xx/rutorrent?action=setuisettings&v={"webui.fls.view":0,"webui.show_cats":1,"webui.show_dets":1,"webui.needmessage":1,"webui.reqtimeout":30000,"webui.confirm_when_deleting":1,"webui.alternate_color":0,"webui.update_interval":3000,"webui.hsplit":0.88,"webui.vsplit":0.5,"webui.effects":0,"webui.fullrows":0,"webui.no_delaying_draw":1,"webui.search":-1,"webui.speedlistdl":"100,150,200,250,300,350,400,450,500,750,1000,1250","webui.speedlistul":"100,150,200,250,300,350,400,450,500,750,1000,1250","webui.ignore_timeouts":0,"webui.retry_on_error":120,"webui.closed_panels":{"ptrackers":0,"pstate":0,"plabel":0,"flabel":0,"prss":0},"webui.timeformat":0,"webui.dateformat":0,"webui.speedintitle":0,"webui.log_autoswitch":1,"webui.show_labelsize":1,"webui.lang":"en","webui.trt.colwidth":[200,100,60,100,100,100,60,60,60,60,60,60,60,80,100,90,200,100,100,60,60,75,75,75,100,100],"webui.trt.colenabled":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"webui.trt.colorder":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],"webui.trt.sindex":-1,"webui.trt.rev":0,"webui.trt.sindex2":0,"webui.trt.rev2":0,"webui.fls.colwidth":[200,60,100,100,80],"webui.fls.colenabled":[1,1,1,1,1],"webui.fls.colorder":[0,1,2,3,4],"webui.fls.sindex":-1,"webui.fls.rev":0,"webui.fls.sindex2":0,"webui.fls.rev2":0,"webui.trk.colwidth":[200,60,60,60,60,60,80,85,80,60],"webui.trk.colenabled":[1,1,1,1,1,1,1,1,1,1],"webui.trk.colorder":[0,1,2,3,4,5,6,7,8,9],"webui.trk.sindex":-1,"webui.trk.rev":0,"webui.trk.sindex2":0,"webui.trk.rev2":0,"webui.prs.colwidth":[100,120,60,100,100,100,60,60,60,100],"webui.prs.colenabled":[1,1,1,1,1,1,1,1,1,1],"webui.prs.colorder":[0,1,2,3,4,5,6,7,8,9],"webui.prs.sindex":-1,"webui.prs.rev":0,"webui.prs.sindex2":0,"webui.prs.rev2":0,"webui.plg.colwidth":[150,60,80,80,80,500],"webui.plg.colenabled":[1,1,1,1,1,1],"webui.plg.colorder":[0,1,2,3,4,5],"webui.plg.sindex":-1,"webui.plg.rev":0,"webui.plg.sindex2":0,"webui.plg.rev2":0,"webui.hst.colwidth":[200,100,100,60,100,100,60,60,100,100,100,100],"webui.hst.colenabled":[1,1,1,1,1,1,1,1,1,1,1,1],"webui.hst.colorder":[0,1,2,3,4,5,6,7,8,9,10,11],"webui.hst.sindex":-1,"webui.hst.rev":0,"webui.hst.sindex2":0,"webui.hst.rev2":0,"webui.teg.colwidth":[200,100,60,100,100,100,60,60,60,60,60,60,60,80,100,90,200,100,100,60,60,75,75,75,100,100],"webui.teg.colenabled":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"webui.teg.colorder":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],"webui.teg.sindex":-1,"webui.teg.rev":0,"webui.teg.sindex2":0,"webui.teg.rev2":0,"webui.rss.colwidth":[200,100,60,100,100,100,60,60,60,60,60,60,60,80,100,90,200,100,100,60,60,75,75,75,100,100],"webui.rss.colenabled":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"webui.rss.colorder":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],"webui.rss.sindex":-1,"webui.rss.rev":0,"webui.rss.sindex2":0,"webui.rss.rev2":0,"webui.fsh.colwidth":[210,60,120,80,310],"webui.fsh.colenabled":[1,1,1,1,1],"webui.fsh.colorder":[0,1,2,3,4],"webui.fsh.sindex":-1,"webui.fsh.rev":0,"webui.fsh.sindex2":0,"webui.fsh.rev2":0,"webui.flm.colwidth":[210,60,120,80,80],"webui.flm.colenabled":[1,1,1,1,1],"webui.flm.colorder":[0,1,2,3,4],"webui.flm.sindex":-1,"webui.flm.rev":0,"webui.flm.sindex2":0,"webui.flm.rev2":0,"webui.tasks.colwidth":[100,100,200,100,110,110,110],"webui.tasks.colenabled":[1,1,1,1,1,1,1],"webui.tasks.colorder":[0,1,2,3,4,5,6],"webui.tasks.sindex":-1,"webui.tasks.rev":0,"webui.tasks.sindex2":0,"webui.tasks.rev2":0,"webui.fManager.timef":"%d-%M-%y %h:%m:%s","webui.fManager.permf":1,"webui.fManager.histpath":5,"webui.fManager.stripdirs":1,"webui.fManager.showhidden":1,"webui.fManager.cleanlog":0,"webui.fManager.arcnscheme":"new","webui.fManager.scrows":12,"webui.fManager.sccols":4,"webui.fManager.scwidth":300}
```

**Comment by Novik** [comment]
> at XMLHttpRequest.send (chrome-extension://hdokiejnpgwwkedhajhdlcewhuplioahd/xhrExtension.js:2:51)

Try to disable this extension.

**Comment by mudboy** [comment]
That sorted it, it was the last pass extension.

**Comment by Novik** [comment]
Really this is my error - query parameter must be encoded. Will be fixed soon as possible.
