### ISSUE TITLE
Bad response from server: (500 [error,getplugins]) Internal Server Error

### ISSUE THREAD

**Issue by cbrace** [Novik/ruTorrent#1836]
Hi all,

I am seeing this error message in the webGUI:

> Bad response from server: (500 [error,getplugins]) Internal Server Error

I see this in the nginx error log:

2019/02/19 10:59:23 [error] 48155#101476: *12 FastCGI sent in stderr: "PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /usr/local/www/ruTorrent-master/php/util.php:239
Stack trace:
#0 /usr/local/www/ruTorrent-master/plugins/lookat/lookat.php(60): safe_json_encode(Array)
#1 /usr/local/www/ruTorrent-master/plugins/lookat/init.php(9): rLook->get()
#2 /usr/local/www/ruTorrent-master/php/getplugins.php(495): require_once('/usr/local/www/...')
#3 {main}
  thrown in /usr/local/www/ruTorrent-master/php/util.php on line 239" while reading response header from upstream, client: 192.168.2.37, server: localhost, request: "GET /rutorrent/php/getplugins.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "pluto", referrer: "http://pluto/rutorrent/"

Any ideas about what is going wrong here?

I am running 
freebsd v11.2
rtorrent v0.9.7_3 
rutorrent v3.8 
nginx v1.14.2_3,2

TIA

**Comment by Novik** [comment]
Try to install JSON php extension.
On the normal systems this extension is a part of PHP core - http://php.net/manual/en/json.installation.php
May be FreeBSD is not a normal system, or you use too old PHP version.

**Comment by cbrace** [comment]
```
<?php
	// configuration parameters

	// for snoopy client
	@define('HTTP_USER_AGENT', 'Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0', true);
	@define('HTTP_TIME_OUT', 30, true);	// in seconds
	@define('HTTP_USE_GZIP', true, true);
	$httpIP = null;				// IP string. Or null for any.

	@define('RPC_TIME_OUT', 5, true);	// in seconds

	@define('LOG_RPC_CALLS', false, true);
	@define('LOG_RPC_FAULTS', true, true);

	// for php
	@define('PHP_USE_GZIP', false, true);
	@define('PHP_GZIP_LEVEL', 2, true);

	$schedule_rand = 10;			// rand for schedulers start, +0..X seconds

	$do_diagnostic = true;
	$log_file = '/tmp/errors.log';		// path to log file (comment or leave blank to disable logging)

	$saveUploadedTorrents = true;		// Save uploaded torrents to profile/torrents directory or not
	$overwriteUploadedTorrents = false;     // Overwrite existing uploaded torrents in profile/torrents directory or make unique name

	$topDirectory = '/';			// Upper available directory. Absolute path with trail slash.
	$forbidUserSettings = false;

	$scgi_port = 5040;
	$scgi_host = "127.0.0.1";

	// For web->rtorrent link through unix domain socket 
	// (scgi_local in rtorrent conf file), change variables 
	// above to something like this:
	//
	// $scgi_port = 0;
	// $scgi_host = "unix:///tmp/rpc.socket";

	$XMLRPCMountPoint = "/RPC2";		// DO NOT DELETE THIS LINE!!! DO NOT COMMENT THIS LINE!!!

	$pathToExternals = array(
		"php" 	=> '',			// Something like /usr/bin/php. If empty, will be found in PATH.
		"curl"	=> '',			// Something like /usr/bin/curl. If empty, will be found in PATH.
		"gzip"	=> '',			// Something like /usr/bin/gzip. If empty, will be found in PATH.
		"id"	=> '',			// Something like /usr/bin/id. If empty, will be found in PATH.
		"stat"	=> '',			// Something like /usr/bin/stat. If empty, will be found in PATH.
	);

	$localhosts = array( 			// list of local interfaces
		"127.0.0.1",
		"localhost",
	);

	$profilePath = '../share';		// Path to user profiles
	$profileMask = 0777;			// Mask for files and directory creation in user profiles.
						// Both Webserver and rtorrent users must have read-write access to it.
						// For example, if Webserver and rtorrent users are in the same group then the value may be 0770.

	$tempDirectory = null;			// Temp directory. Absolute path with trail slash. If null, then autodetect will be used.

	$canUseXSendFile = false;		// If true then use X-Sendfile feature if it exist

	$locale = "UTF8";
```

**Comment by cbrace** [comment]
```
cat nginx.conf | grep -v \# | grep -v ^$
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       80;
        root /usr/local/www;
        server_name  localhost;
        location / {
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/www/nginx-dist;
        }
        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
 	location /RPC2 {
	include scgi_params;
 	scgi_pass 127.0.0.1:5040;
	}	
    }
}
```

**Comment by cbrace** [comment]
Fixed, thanks
