### ISSUE TITLE
Call to undefined method get_magic_quotes_gpc() with php version > 8

### ISSUE THREAD

**Issue by solarus** [Novik/ruTorrent#2166]
Currently seeing the following exceptions when trying to run rutorrent with php version > 8:

```
2021-04-11 11:32:41: mod_fastcgi.c.487) FastCGI-stderr:PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /usr/share/webapps/rutorrent/php/util.php:58
2021-04-11 11:32:41: mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
2021-04-11 11:32:41: mod_fastcgi.c.487) FastCGI-stderr:#0 /usr/share/webapps/rutorrent/php/util.php(67): fix_magic_quotes_gpc()
2021-04-11 11:32:41: mod_fastcgi.c.487) FastCGI-stderr:#1 /usr/share/webapps/rutorrent/php/getplugins.php(3): require_once('/usr/share/weba...')
2021-04-11 11:32:41: mod_fastcgi.c.487) FastCGI-stderr:#2 {main}
2021-04-11 11:32:41: mod_fastcgi.c.487) FastCGI-stderr:  thrown in /usr/share/webapps/rutorrent/php/util.php on line 58
```

Seems this method was removed when checking latest documentation:

- https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

> This function has been DEPRECATED as of PHP 7.4.0, and REMOVED as of PHP 8.0.0. Relying on this function is highly discouraged.

Since this method has just been returning false for a couple versions anyway could probably be fixed in a backwards compatible way same as was done for e.g. phpmyadmin:

- https://github.com/phpmyadmin/phpmyadmin/issues/8837#issuecomment-124681538

**Comment by solarus** [comment]
Nvm see now that this commit, that is already merged, should probably fix it as (but I did not have that running locally):

* https://github.com/Novik/ruTorrent/commit/354fca43b392eb10251a0f7214c9eccabf354227#diff-ee41a3383919c1b2ec7309d0d9f9a4f0dd48191bfa3ad50eb82c48006684bbc2

Will a later version
