### ISSUE TITLE
Screenshot not working 

### ISSUE THREAD

**Issue by colinborins** [Novik/ruTorrent#2420]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Google Chrome 97.0.4692.71  ruTorrent: 4.0 PHP: PHP81 OS: Truenas 13.0 running 
Freebsd 13.0-RELEASE-p11

### Tell us how you installed ruTorrent

Followed the following guide: https://forums.freebsd.org/threads/freebsd-install-rtorrent-and-rutorrent-on-lighttpd-full-guide.85230/#post-567706

### Describe the bug

Screenshot wont work. It will only show done and not take any screenshots

**Comment by colinborins** [comment]
﻿
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
VM350 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM350 content_script.js:1:1)
VM413 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM413 content_script.js:1:1)
VM465 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM465 content_script.js:1:1)
VM571 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM571 content_script.js:1:1)
content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at content_script.js:1:1)
﻿
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
VM350 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM350 content_script.js:1:1)
VM413 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM413 content_script.js:1:1)
VM465 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM465 content_script.js:1:1)
VM571 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM571 content_script.js:1:1)
content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at content_script.js:1:1)
