### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded from RangeError

### ISSUE THREAD

**Issue by YaPaY** [Novik/ruTorrent#2458]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Brave Mac
4.0.2

### What were you trying to do?

Right Click on any torrent

### What us the error message?

JS error: http://192.168.1.1/rutorrent/js/jquery.js?v=402 : 2 Uncaught RangeError: Maximum call stack size exceeded
<img width="380" alt="Monosnap ruTorrent v4 0 2 2023-03-09 20-15-10" src="https://user-images.githubusercontent.com/705923/224159866-37f960c5-47fc-42ef-96bd-de1776bf32e9.png">

### Give us the stack trace.

Uncaught RangeError: Maximum call stack size exceeded from RangeError: Maximum call stack size exceeded
    at ot (http://192.168.1.1/rutorrent/js/jquery.js?v=402:2:58859)
    at Synchronizetion.window.requestAnimationFrame.window.setTimeout (chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:35:13)
    at ot (http://192.168.1.1/rutorrent/js/jquery.js?v=402:2:58905)
    at Synchronizetion.window.requestAnimationFrame.window.setTimeout (chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:35:13)
    at ot (http://192.168.1.1/rutorrent/js/jquery.js?v=402:2:58905)
    at Synchronizetion.window.requestAnimationFrame.window.setTimeout (chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:35:13)
    at ot (http://192.168.1.1/rutorrent/js/jquery.js?v=402:2:58905)
    at Synchronizetion.window.requestAnimationFrame.window.setTimeout (chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:35:13)
    at ot (http://192.168.1.1/rutorrent/js/jquery.js?v=402:2:58905)
    at Synchronizetion.window.requestAnimationFrame.window.setTimeout (chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:35:13)

**Comment by Novik** [comment]
https://github.com/WordPress/gutenberg/issues/37397#issuecomment-1273448249
